<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Evoluzione.IndependenceDay.Contracts\Evoluzione.IndependenceDay.Contracts.csproj" />
    <ProjectReference Include="..\..\Shared\Evoluzione.IndependenceDay.Infrastructure\Evoluzione.IndependenceDay.Infrastructure.csproj" />
    <ProjectReference Include="..\Evoluzione.IndependenceDay.Space.Messages\Evoluzione.IndependenceDay.Space.Messages.csproj" />
  </ItemGroup>
</Project>
