<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Evoluzione.IndependenceDay.Earth.Domain\Evoluzione.IndependenceDay.Earth.Domain.csproj" />
    <ProjectReference Include="..\Evoluzione.IndependenceDay.Earth.ReadModel\Evoluzione.IndependenceDay.Earth.ReadModel.csproj" />
  </ItemGroup>
</Project>
