<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Evoluzione.IndependenceDay.Space.Domain\Evoluzione.IndependenceDay.Space.Domain.csproj" />
    <ProjectReference Include="..\Evoluzione.IndependenceDay.Space.ReadModel\Evoluzione.IndependenceDay.Space.ReadModel.csproj" />
  </ItemGroup>
</Project>
