<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
    <ProjectReference Include="..\Evoluzione.IndependenceDay.Space.Messages\Evoluzione.IndependenceDay.Space.Messages.csproj" />
    <ProjectReference Include="..\..\Shared\Evoluzione.IndependenceDay.Infrastructure\Evoluzione.IndependenceDay.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Shared\Evoluzione.IndependenceDay.Contracts\Evoluzione.IndependenceDay.Contracts.csproj" />
  </ItemGroup>
</Project>
